all:
  vars:
      ansible_connection: ssh
      ansible_user: kafka
      ansible_become: true
      ansible_ssh_private_key_file: ~/.ssh/migrations-SSHKey
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

zookeeper:
  hosts:
    migrations-migrations-destination-subnet-zk-0:
    migrations-migrations-destination-subnet-zk-1:
    migrations-migrations-destination-subnet-zk-2:

kafka_broker:
  hosts:
    migrations-migrations-destination-subnet-broker-0:
      broker_id: 0
    migrations-migrations-destination-subnet-broker-1:
      broker_id: 1
    migrations-migrations-destination-subnet-broker-2:
      broker_id: 3

schema_registry:
  hosts:
    migrations-migrations-destination-subnet-sr-0:

ksql:
  hosts:
    migrations-migrations-destination-subnet-ksql-0:

kafka_connect:
  hosts:
    migrations-migrations-destination-subnet-connect-0:

control_center:
  hosts:
    migrations-migrations-destination-subnet-c3-0:
